### ISSUE TITLE
Segfault when uploading changes to OSM server

### ISSUE THREAD

**Issue by julietkilo** [openstreetmap/merkaartor#105]
Hi,

Merkaartor 0.18.2 crashes on my Ubuntu 16.04 when uploading map changes to the OSM server. This behavior was observed directly after updating from Ubuntu 15.10 to 16.04 where the Merkaartor version changes from 0.18 to 0.18.2. Fortunately I saved the changes to a file that reproduces the bug on my machine each time.

[osmfile.zip](https://github.com/openstreetmap/merkaartor/files/288401/osmfile.zip)

Thanks
Jens

**Comment by Krakonos** [comment]
Hi! I think this is bug #38 and was fixed in e8d3bdfc6b4496df3a41c039861bb07fb72793ff . It would be great if you could test the latest git version. There are instructions in the INSTALL file. You will probably need these packages installed:

gdb libgdal-dev libproj-dev libqt4-xml libqt4-network libqt4-gui libqt4-svg libqt4-webkit libqt4-dev qt4-qmake

(or their qt equivalent, but I'm not sure how they are called in ubuntu right now).

I can't really test with that file without some changes first, as I can't, in a good conscience, push it to the live servers and the test server doesn't have the proper nodes in there...

**Comment by julietkilo** [comment]
Hi again,
unfortunately I have not luck with building from source.
Do I need any parameters when calling "qmake"?
I didn't get any response from qmake or qmake-qt4.

jens@black:~/workspace/merkaartor/merkaartor$ qmake
jens@black:~/workspace/merkaartor/merkaartor$ 

jens@black:~/workspace/merkaartor/merkaartor$ qmake-qt4
jens@black:~/workspace/merkaartor/merkaartor$ 

jens@black:~/workspace/merkaartor/merkaartor$ qmake -r
Reading /home/jens/workspace/merkaartor/merkaartor/src/src.pro
Reading /home/jens/workspace/merkaartor/merkaartor/plugins/plugins.pro
 Reading /home/jens/workspace/merkaartor/merkaartor/plugins/background/background.pro
  Reading /home/jens/workspace/merkaartor/merkaartor/plugins/background/MMsBingMapBackground/MMsBingMapBackground.pro
  Reading /home/jens/workspace/merkaartor/merkaartor/plugins/background/MWalkingPapersBackground/MWalkingPapersBackground.pro
  Reading /home/jens/workspace/merkaartor/merkaartor/plugins/background/MGeoTiffBackground/MGeoTiffBackground.pro
  Reading /home/jens/workspace/merkaartor/merkaartor/plugins/background/MGdalBackground/MGdalBackground.pro
jens@black:~/workspace/merkaartor/merkaartor$ 

jens@black:~/workspace/merkaartor/merkaartor$ qmake -makefile Makefile
/home/jens/workspace/merkaartor/merkaartor/Makefile:9: Parse Error ('first: make_default')
Error processing project file: Makefile
jens@black:~/workspace/merkaartor/merkaartor$

**Comment by Krakonos** [comment]
qmake or qmake-qt4 won't output anything, but that's good. qmake -r outputs a bit (and yours look good). Any of these is enough though!

After you call qmake, just call plain "make", or "make -jX" where X is the number of cpu cores you want busy.

**Comment by julietkilo** [comment]
Building merkaartor works perfectly. Upload data works also now.
Ubuntu 16.04
Merkaartor version 0.18.2-92-g29833c3
Qt version 4.8.7
PROJ.4 version 4.9.2
GDAL version 1.11.3

Great work. Thanks!
