### ISSUE TITLE
WMS loading problem - Mac OSX

### ISSUE THREAD

**Issue by frettie** [openstreetmap/merkaartor#115]
Hi, when i want open (actual version 0.18.3 rc1) WMS (CUZK KM, GIS Kraje Vysočina, ...) i set wms layer and not see anyone.

--- cz
Ahoj, dobrý den,
pokud se pokusím otevřít (i základní, integorvané) WMSka (tak i CUZK nebo GIS kraje Vysočina), tak se nic nezobrazí, Nastavím layer a nic, nevím co nastavit, či zda je špatně něco v systému. 

Díky za radu.

**Comment by Krakonos** [comment]
Hi!

Is this something that worked in recent versions, like 0.18.2? I didn't touch most of the WMS infrastructure, but your configuration might be out of date.

I just tried my old UHUL configuration and the server returns 404. But CZUK ortofoto works just fine. I used this specific (tiled) server configuration: 

```
http://geoportal.cuzk.cz/WMS_ORTOFOTO_PUB/WMService.aspx?VERSION=1.1.1&SERVICE=WMS&LAYERS=GR_ORTFOTORGB&SRS=EPSG:3857&STYLES=&FORMAT=image/jpeg
```

If you prefer help in czech, feel free to email me at krakonos@krakonos.org. Also, feel free to post any Mac OS X specific bugs, as I don't know about anyone using merkaartor on mac currently, and I only have a vm...

**Comment by frettie** [comment]
Hi!
thanks a lot.

I tried some other WMS services and it was ok.

Then, i tried CUZK WM service and it was ok. Maybe there is problem with
some parameters? I dont know, but now its ok. Thanks!

J.

On Wed, Jun 22, 2016 at 10:29 PM, Ladislav Láska <notifications@github.com>
wrote:

> Hi!
>
> Is this something that worked in recent versions, like 0.18.2? I didn't
> touch most of the WMS infrastructure, but your configuration might be out
> of date.
>
> I just tried my old UHUL configuration and the server returns 404. But
> CZUK ortofoto works just fine. I used this specific (tiled) server
> configuration:
>
> http://geoportal.cuzk.cz/WMS_ORTOFOTO_PUB/WMService.aspx?VERSION=1.1.1&SERVICE=WMS&LAYERS=GR_ORTFOTORGB&SRS=EPSG:3857&STYLES=&FORMAT=image/jpeg
>
> If you prefer help in czech, feel free to email me at
> krakonos@krakonos.org. Also, feel free to post any Mac OS X specific
> bugs, as I don't know about anyone using merkaartor on mac currently, and I
> only have a vm...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openstreetmap/merkaartor/issues/115#issuecomment-227866686>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABEtwdYpCwEWTDsQR2ZcDRKvHtnRcibcks5qOZsMgaJpZM4I8KtB>
> .
>



-- 
S pozdravem,
Jirka Sedláček
---
jirisedlacek@gmail.com

**Comment by Krakonos** [comment]
Possibly. The WMS servers are somewhat magic, and some require specific parameters in order to function. I often find the problem isn't that they are not working (though they are not paragons of reliability), but rather they are returning blank pages...

Unfortunately, both of these possibilities manifest themselves as white images. I'll probably do something about it in the future.

I consider this problem solved, feel free to let me know if you have more trouble!
