### ISSUE TITLE
Requires only libproj.so.9

### ISSUE THREAD

**Issue by CriOnsKry** [openstreetmap/merkaartor#122]
Requires only libproj.so.**9**, but I have libproj.so.**12**!!!
I made a copy *.so.12, and renamed in *.so.9. =_=

**Comment by Krakonos** [comment]
Hi! This looks like your Merkaartor has been built with earlier version of proj.4. Could you elaborate on your OS and wether you built it yourself or used a package?

In case it's a prebuilt package, it should be reported to the package maintainer. 
If you built yourself, `make clean; qmake -r; make; ...` should fix your problem.

**Comment by CriOnsKry** [comment]
My OS is ArchLinux.
I decided my problem. However, compiling require this library. When installing from the repository, the editor does not open until I solved the problem. Just fix this inconvenience.
I Used Google Translate.

**Comment by Krakonos** [comment]
I reported the issue to Arch maintainer. I expect it being fixed soon, but there is only 0.18.2 available. I would recommend using merkaartor-git from AUR in the meantime, as it contains a lot of additional fixes.

**Comment by CriOnsKry** [comment]
> If you built yourself, make clean; qmake -r; make; ... should fix your problem.
`merkaartor>>>$ qmake -r
Reading /home/arch/Downloads/merkaartor/src/src.pro
Project ERROR: Unknown module(s) in QT: webenginewidgets
`
m?

**Comment by Krakonos** [comment]
You probably have qt4 installed and set as default. Try `qmake-qt5 -r`

**Comment by Krakonos** [comment]
Btw. the merkaartor-git package in AUR seems to work fine, though you might need to install qt5-webengine manually due to a missing dependency. I will look into fixing that.

**Comment by CriOnsKry** [comment]
> You probably have qt4 installed and set as default. Try qmake-qt5 -r

The same conclusion. And with *qmake-qt4 -r* too.

> Btw. the merkaartor-git package in AUR seems to work fine, though you might need to install qt5-webengine manually due to a missing dependency. I will look into fixing that.

Later I check. But most of all I have this package.
(Google Translate)

**Comment by CriOnsKry** [comment]
> Btw. the merkaartor-git package in AUR seems to work fine, though you might need to install qt5-webengine manually due to a missing dependency. I will look into fixing that.

Work, thanks;)

**Comment by Krakonos** [comment]
Btw. the report I made to Arch is here: https://bugs.archlinux.org/task/51192

**Comment by Krakonos** [comment]
Fixed by the Arch devs. They also updated to the 0.18.3 release.
