### ISSUE TITLE
Provide more TMS and WMS provider.

### ISSUE THREAD

**Issue by s8321414** [openstreetmap/merkaartor#123]
Like iD or JOSM, I think we should provide more TMS and WMS provider by default, ot at least can be seclected from a list.

**Comment by Krakonos** [comment]
Sure thing, it's already listed as #55. I will completely rework the imagery tools, to provide more user-friendly interface, offering to add more imagery from the index mentioned in #55. 

Closing as a duplicate, feel free to comment on the issue mentioned.

**Comment by s8321414** [comment]
ah, OK.
