### ISSUE TITLE
TMS dialog in recent editions recodes %1 as %251.

### ISSUE THREAD

**Issue by afarlie** [openstreetmap/merkaartor#134]
I've noticed that on occasion Merkattor, will convert a %1 into %251.  Is this a known issue?

**Comment by Krakonos** [comment]
Yes, this is a known bug, reported as #88. Unfortunately, I haven't had time to look into it, but I might do it soon. Please see a workaround in the mentioned bug (essentially changing that %25 back to % in the stored xml).
