### ISSUE TITLE
Depreciation strategy for legacy OS

### ISSUE THREAD

**Issue by afarlie** [openstreetmap/merkaartor#135]
OS and libraries develop over time. 
It would therefore be appreciated if there was a documented stragey in respect of those users like myself that are still running on legacy OS.

**Comment by Krakonos** [comment]
Well, that depends. If your os is really old, you should stick with the old version of the program. Could you specify what legacy is for you? For example, in terms of qt version available.

**Comment by afarlie** [comment]
I am still using XP, so it's in relation to whatever version QT is still supported on that (Qt5?), I'm still using 0.17 series Merkattor for now.

**Comment by Krakonos** [comment]
I'm not sure about that. Can you try out the 0.18.3, 32bit version? 

http://www.merkaartor.be/files/merkaartor-0.18.3-32bit.exe

It's already compiled with qt5 (5.3 or 5.5, I don't remember), and could work. Alternatively, you could try compiling using msys2 (see docs) to get an up to date version. Let me know if it works!

**Comment by afarlie** [comment]
Beated response 0.18 worked , apart from plentty of errors with the "Get Services" button in the TMS servers editor.
