### ISSUE TITLE
Document how to configure the donwload of OSM data from alternate servers.

### ISSUE THREAD

**Issue by afarlie** [openstreetmap/merkaartor#136]
I'd like to know how to configure the program so I can map old railways in the United Kingdom  ( from NPE/7th series) maps, directly. 

This is data that would not be destined for the main OSM database, that that of a database hosted on an alternate server platform such as openhistoricalmap.org

**Comment by Krakonos** [comment]
Sure, just go to tool -> preferences -> data, you can insert your own servers there. You can have multiple entries prefilled to allow easy switching.

**Comment by afarlie** [comment]
Thanks
