### ISSUE TITLE
Merkaartor does not exit properly when main window is closed before splash vanishes

### ISSUE THREAD

**Issue by Krakonos** [openstreetmap/merkaartor#15]
In the old redmine bug 3078, Sven Lankes reported:

When I quit merkaartor very early in the startup process (while the splash-screen is still shown) it closes it's window and hangs.

This is using the 0.16.1 fedora package.

---

Still happens in current master.

**Comment by zander** [comment]
Can't reproduce.

I even uncommented the closing of the splash, to make sure I had plenty of time (the splash is a flash here), but the app closes just fine.

**Comment by Krakonos** [comment]
Neither can I. Also, I think I did some fixing regarding this issue - but I can't find it anywhere. It could have been an issue with Qt. Looking at the code in Main.cpp, the startup sequence seems reasonable. Therefore,I'm closing this issue. Thanks for looking it over!
