### ISSUE TITLE
No window icon on Plasma Wayland

### ISSUE THREAD

**Issue by stikonas** [openstreetmap/merkaartor#150]
On Plasma Wayland session merkaartor has no icon.

You need to either rename merkaartor.desktop->org.merkaartor.merkaartor.desktop

or 

call QGuiApplication::setDesktopFileName(QStringLiteral("merkaartor"));

I guess the first option is better due to freedesktop.org icon naming standards.

**Comment by Krakonos** [comment]
Hi! I commited the renaming change in 85ee9b1 (not merged yet). Can you verify if this fixes the issue? I do not have any setup I could test. I will try to do a bit more testing when I get back home (in about a month).

**Comment by stikonas** [comment]
I'll be getting back home only in June too. I might verify then.

On 19 May 2018 21:46:42 GMT+10:00, "Ladislav Láska" <notifications@github.com> wrote:
>Hi! I commited the renaming change in 85ee9b1 (not merged yet). Can you
>verify if this fixes the issue? I do not have any setup I could test. I
>will try to do a bit more testing when I get back home (in about a
>month).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openstreetmap/merkaartor/issues/150#issuecomment-390399575

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stikonas** [comment]
@Krakonos Yes, that patch fixes the issue. Just tested.

**Comment by Krakonos** [comment]
Thanks, I'm considering this issue fixed.
