### ISSUE TITLE
UI consistency with OpenStreetMap terminology: Replace "Road" with "Way"

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/merkaartor#160]
The user interface uses "Road" to refer to any linear feature.  The standard OSM term is "Way", used not just to refer to roads and paths but also to rivers/streams, fences, power lines and anything else which is not an area or node.  It would be less confusing if Merkaartor used "Way" in the UI also.

A quick survey shows "Road" used in:

  Menu bar - Show - Show directional arrows
  Menu bar - Create - Road (also "Double carriage way" here could say "Parallel way")
  Menu bar - Road menu
  Tool bar - Road (tool tip "Create new road")
  Tool bar - Detach, Split, Break, Join, Reverse tool tips
  Properties - Road dockable pane
  Features dockable pane
  Undo dockable pane ("Create node in road")
  Popup menu - Road submenu

**Comment by Krakonos** [comment]
Yes, let's fix that. If anyone feels like submitting a PR, I'd appreciate it!
