### ISSUE TITLE
Download map error

### ISSUE THREAD

**Issue by mvalcke** [openstreetmap/merkaartor#164]
Well, title says it all. Any map I try to download, I get a similar message> Any help please?
I'm on Mac OS using Merkaartor v0.18.4 (QT4 download)

Error:

https://www.openstreetmap.org/api/0.6/map?bbox=-7.071000,37.374700,19.410700,57.017000 - server replied: Bad Request

**Comment by joernheissler** [comment]
It looks like you tried to download half of Europe. Select a *much* smaller part of the map.
E.g. when you go to "Download", navigate in the map and select a part inside the map (click into the map and draw a box).

**Comment by Krakonos** [comment]
As @joernheissler said, the map area is too large. Merkaartor currently bears the same limitation as OSM API, as it cannot split the request into multiple queries.

In this case, the query is unreasonably large and is not a smart thing to do anyway. If you want to download overall map data, look up OSM snapshots.

Looking at the dialog, I noticed you probably tried to download the "Europe" bookmark. I guess this is a relict of past times when OSM was mostly empty. I will remove it.

**Comment by Krakonos** [comment]
I have removed the misleading bookmarks in 64a94321bce7456818fbe05a20c0e807ef705743 . The change will affect new installations after the next release.

Feel free to contact me if you have any other issues with Merkaartor.
