### ISSUE TITLE
Add AppStream metadata

### ISSUE THREAD

**Issue by City-busz** [openstreetmap/merkaartor#174]
[AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/) is a cross-distribution effort for enhancing the way we interact with the software repositories provided by (Linux) distributions by standardizing software component metadata.

Please include a metainfo XML file like the [attached one](https://github.com/openstreetmap/merkaartor/files/2715791/org.merkaartor.merkaartor.appdata.xml.txt) in the upstream project, and install it into '/usr/share/metainfo/org.merkaartor.merkaartor.appdata.xml' during the build process, so distributions could use it.

**Comment by Krakonos** [comment]
I see you have helped yourself in PR #218 . Thanks! Can I consider this issue solved?

**Comment by City-busz** [comment]
Yes, of course :)
