### ISSUE TITLE
Access Keychain when uploading - Mac OSX

### ISSUE THREAD

**Issue by Kampfhamster** [openstreetmap/merkaartor#175]
When uploading to OSM the App wants access to unrelated Passwords Keychain Data - MacOS(10.14.1)

**Comment by Krakonos** [comment]
Hi!

Thanks for the report. It might be this qt issue:

https://bugreports.qt.io/browse/QTBUG-69396?focusedCommentId=411714&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

Could you try to run Merkaartor with the environment variable QT_SSL_USE_TEMPORARY_KEYCHAIN=1?

On commandline:
```
QT_SSL_USE_TEMPORARY_KEYCHAIN=1 merkaartor
```
