### ISSUE TITLE
Support for PROJ 6.0.0

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/merkaartor#178]
Merkaartor still uses `proj_api.h` which is deprecated in PROJ 6.0.0 and will be removed in PROJ 7.0.0 (scheduled for March 2020).

When using `proj_api.h` with PROJ 6.0.0 `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` needs to be added to `CFLAGS` to prevent a compiler error.

Merkaartor should be updated to (also) support the `proj.h` API.

**Comment by z3ntu** [comment]
This makes the macOS CI fail currently as they've upgraded to Proj 6.0.0

A start of migrating to the new api (`proj.h`) is the following but unfortunately the rest of the API isn't just changing the names of the functions.
```diff
diff --git a/src/Main.cpp b/src/Main.cpp
index e0fa68bf..69e6c85f 100644
--- a/src/Main.cpp
+++ b/src/Main.cpp
@@ -9,7 +9,7 @@
 #include <qtsingleapplication.h>
 #include "MainWindow.h"
 #include "Preferences/MerkaartorPreferences.h"
-#include "proj_api.h"
+#include "proj.h"
 #include "gdal_version.h"
 #include "Global.h"
 
@@ -137,8 +137,7 @@ int main(int argc, char** argv)
 
     qDebug() << "**** " << QDateTime::currentDateTime().toString(Qt::ISODate) << " -- Starting " << QString("%1 %2").arg(qApp->applicationName()).arg(STRINGIFY(VERSION));
     qDebug() <<	"-------" << QString("using Qt version %1 (built with %2)").arg(qVersion()).arg(QT_VERSION_STR);
-    QString projVer = QString(STRINGIFY(PJ_VERSION));
-    qDebug() <<	"-------" << QString("using PROJ4 version %1.%2.%3").arg(projVer.left(1)).arg(projVer.mid(1, 1)).arg(projVer.right(1));
+    qDebug() <<	"-------" << QString("using PROJ4 version %1.%2.%3").arg(PROJ_VERSION_MAJOR).arg(PROJ_VERSION_MINOR).arg(PROJ_VERSION_PATCH);
     qDebug() <<	"-------" << QString("using GDAL version %1").arg(GDAL_RELEASE_NAME);
     qDebug() << "-------" << "with arguments: " << QCoreApplication::arguments();
 
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
index e0f39ead..c5032765 100755
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -2121,8 +2121,7 @@ void MainWindow::on_helpAboutAction_triggered()
     dlg.setWindowFlags(dlg.windowFlags() | Qt::MSWindowsFixedSizeDialogHint);
     About.Version->setText(About.Version->text().arg(STRINGIFY(REVISION)));
     About.QTVersion->setText(About.QTVersion->text().arg(qVersion()).arg(QT_VERSION_STR));
-    QString projVer = QString(STRINGIFY(PJ_VERSION));
-    About.Proj4Version->setText(About.Proj4Version->text().arg(QString("%1.%2.%3").arg(projVer.left(1)).arg(projVer.mid(1, 1)).arg(projVer.right(1))));
+    About.Proj4Version->setText(About.Proj4Version->text().arg(QString("%1.%2.%3").arg(PROJ_VERSION_MAJOR).arg(PROJ_VERSION_MINOR).arg(PROJ_VERSION_PATCH)));
     About.GdalVersion->setText(About.GdalVersion->text().arg(GDAL_RELEASE_NAME));
 
     QFile ct(":/Utils/CHANGELOG");
diff --git a/src/common/Projection.h b/src/common/Projection.h
index efb9d92a..1e4b46d8 100644
--- a/src/common/Projection.h
+++ b/src/common/Projection.h
@@ -9,8 +9,8 @@
 #ifndef _MOBILE
 #include "MerkaartorPreferences.h"
 
-#include <proj_api.h>
-typedef projPJ ProjProjection;
+#include <proj.h>
+typedef PJ* ProjProjection;
 
 #endif // _MOBILE
 

```

**Comment by pabs3** [comment]
FYI, due to the lack of a fix for this issue, Merkaartor was removed from Debian:

https://bugs.debian.org/933492

**Comment by Krakonos** [comment]
The PR implementing the workaround is merged, but we should look into the migration. It seems 6.0 version is widely available now. I'd appreciate any help regarding the migration.

**Comment by OliverHe** [comment]
The workaround no longer works for Proj 8:
[https://people.freebsd.org/~lbartoletti/logs/proj8/merkaartor-0.19.0.log](https://people.freebsd.org/~lbartoletti/logs/proj8/merkaartor-0.19.0.log)   (not my build)

Can this issue be re-opened, or should a new one be made?

**Comment by sebastic** [comment]
The Debian package built successfully with 8.1.1:

 https://buildd.debian.org/status/package.php?p=merkaartor

The FreeBSD buildlog shows `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1`, defining this triggers an error since the `proj_api.h` removal in PROJ 8.0.0:
```C
#ifdef ACCEPT_USE_OF_DEPRECATED_PROJ_API_H
  #error "The proj_api.h header has been removed from PROJ with version 8.0.0"
#endif
```
https://github.com/OSGeo/PROJ/blob/8.2/src/proj.h#L122

You need to drop that from the Makefile:

 https://cgit.freebsd.org/ports/tree/astro/merkaartor/Makefile?id=adb2e11190a24ee858e188f2bb1667fa46edfe4b#n23

See also:

 https://salsa.debian.org/debian-gis-team/merkaartor/-/commit/6e0c44535377ca27611cbfb1786fa0a3f08fe113

**Comment by Krakonos** [comment]
@OliverHe I confirm @sebastic  is correct, the 0.19 release and current master fully support 8.x series of PROJ and the legacy macro should not be introduced. If you find other issues, please open a separate ticket.
