### ISSUE TITLE
Fix & document Windows build system

### ISSUE THREAD

**Issue by Krakonos** [openstreetmap/merkaartor#18]
The Windows build is mostly working, but waits for the Qt 5.4.2, which fixes a bug in QtNetworking, causing crash on non-debug builds (patch is already accepted). Merkaartor builds fine with MSYS2 on 64bit systems, but is not at all tested on 32bits, and the process is documented in INSTALL since 2481d3ad51db0bc70a1f8b6a079fef9dd5a82964 (qt5 branch). More testing is required though.

**Comment by stephan75** [comment]
Hi, is there anything we can do as normal merkaartor users by testing or similar, in order to get an installer for windows systems (and other OS) based on recent code base available?

**Comment by Krakonos** [comment]
Not much right now. I'm waiting for the Qt 5.4.2 release (expected in mid april, that is, in about a week), which should fix a showstopper bug in the release build (that is, the build that is not 500MB). I will be making a Windows installer then. The OS X is in the works too, I already have a Mac handy, but have not installed the toolchain there.

**Comment by stephan75** [comment]
@Krakonos ... Hello Ladislav,
As I have no helpful knowledge in programming I am only able to do some cherry-picking in the news, but it seems we have a release of Qt5.4.2 now:
https://blog.qt.io/blog/2015/06/02/qt-5-4-2-released/
Do we have that showstopper bug solved there?

**Comment by Krakonos** [comment]
Hi!

I've been busy (traveling) for some time. Thanks for the notice, I'll take a
look sometime soon. It *should* be fixed and I'll do a relase as soon as
possible.

> @Krakonos ... Hello Ladislav,
> As I have no helpful knowledge in programming I am only able to do some cherry-picking in the news, but it seems we have a release of Qt5.4.2 now:
> https://blog.qt.io/blog/2015/06/02/qt-5-4-2-released/
> Do we have that showstopper bug solved there?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/openstreetmap/merkaartor/issues/18#issuecomment-118229801

-- 
S pozdravem Ladislav Láska                          <laska@kam.mff.cuni.cz>
Katedra Aplikované Matematiky, MFF UK               tel.: +420 739 464 167

**Comment by Ostpaket** [comment]
Windows installer for 0.18.2 is still not working, neither for x86 nor for x64. <Could not find Qt platform plugin "windows">
I tried some of the solutions that can be found on the web (setting environment variable QT_QPA_PLATFORM_PLUGIN_PATH, copying some "missing" DLLs) - none of this worked. :-(

**Comment by Krakonos** [comment]
Bummer. The platform library is missing from the installer. I've uploaded new files with it bundled, and will update scripts accordingly. As almost noone downloaded it beside you, I've replaced the old ones without name change. Let me know if this fixes it.

**Comment by Ostpaket** [comment]
Wow, that was fast. Thanks a lot! 
It starts now successfully, both 32bit and 64bit. Didn't tried much more yet, though...
Have a safe trip!
