### ISSUE TITLE
Raw GPS tracks displaying is broken

### ISSUE THREAD

**Issue by denizzzka** [openstreetmap/merkaartor#181]
![image](https://user-images.githubusercontent.com/974632/58328156-9f39cd80-7e5b-11e9-9380-5202441ee0a6.png)

**Comment by Krakonos** [comment]
Hi!
I believe this is "not a bug", though a bit annoying. You probably found a spot with too many GPS tracks. Take a look into the "Layers" panel and disable a few (perhaps all). Any suggestions on how to make this number of tracks manageable?

**Comment by denizzzka** [comment]
Not agreed.

Merkaator and Id3 with GPS tracks enabled, on ~same point (around https://www.openstreetmap.org/#map=14/56.1686/92.9765):
![image](https://user-images.githubusercontent.com/974632/62799020-e7d35f80-bb09-11e9-817c-08dd8eb2418b.png)
![image](https://user-images.githubusercontent.com/974632/62799026-ebff7d00-bb09-11e9-9ae6-4dcbcd6f47cc.png)

**Comment by denizzzka** [comment]
I am trying with Merkaartor 0.18.3+ds-5+b1 from Debian

**Comment by Krakonos** [comment]
Well, id is using the layer from osm.org. However, you might be onto something; but it's not that simple. For example the following URL:

https://www.openstreetmap.org/api/0.6/trackpoints?bbox=92.9721,56.1702,92.98,56.1735&page=0

Contains a track segment that results in the pattern above. At the time of writing, it is the very last segment. It looks a lot like a GPS with a poor signal that trid to guess the position based on map data, and put some of the trackpoints on some parallel road. I'm not really sure what to do about it? Thoughts?

At this point I would recommend adding the osm.org layer iD uses and only download the GPS traces in cases you actually want to derivy a geometry from one (and then filter the corrupt one manually).

**Comment by denizzzka** [comment]
> It looks a lot like a GPS with a poor signal that trid to guess the position based on map data

my own tracks with a good signal are also displaying like this

>  I'm not really sure what to do about it? Thoughts?


Pay attention - poor lines are always horizontal. I think system of rendering or storing tracks inside of the Mercator is broken.

Does anyone reproduces this? What versions are you using?

**Comment by Krakonos** [comment]
Let's talk specific. From the link I shared above, I have extracted the segment in question and attached to this issue (downloading via brower and edited in vim to remove the extra segments to minimize the example). It clearly exhibits the behavior I described: note that in the raw gpx the latitude is more or less a rising sequence, the longitude has singular data points that go by 0.001 - 0.005 back and forth. As they are pretty close together, they seem to form horizontal lines.

I verified this in a different viewer and it draws exactly the same trace.

If you can reproduce it on your own traces, would you share a short sequence that you think triggers this problem, so we could test and evaluate? 

(You can upload it to this github issue by drag-and-dropping, but they have to be zipped - github doesn't support .gpx files).

[issue-181.gpx.zip](https://github.com/openstreetmap/merkaartor/files/3488601/issue-181.gpx.zip)

**Comment by Krakonos** [comment]
Btw. I just did a quick calculation and 0.001 difference in longitude is around 62m, which seems to fit the rendering exactly.

Also, I'm testing this on latest master from git. However, it does seem to produce the same behavior.

**Comment by denizzzka** [comment]
I don’t understand what you mean. You want to say that the OSM archive is full of GPS tracks with horizontal problems that look like above picture where track jumps EXACTLY between two nearby roads  and this only appears at Mercarator? And this is not an Merkaartor issue?

**Comment by denizzzka** [comment]
Let's do this: gibe me a reliable point on the map where tracks are perfect by you mind and I will take a screenshot of how it looks at my Merkaartor.

**Comment by Krakonos** [comment]
I mean that if you ask Merkaartor to render a GPX file with a broken track, it renders it. And yes, the osm.org is full of these tracks; and I have found out why.

After looking around the areas, I noticed it always is the last segment from osm.org gpx, and it always doesn't have a name. Looking at the [OSM API reference](https://wiki.openstreetmap.org/wiki/API_v0.6), they state:

> In violation of the GPX standard when downloading public GPX traces through the API, all waypoints of non-trackable traces are randomized (or rather sorted by lat/lon) and delivered as one trackSegment for privacy reasons. 

So they are not segments at all, they are rather sorted points that were uploaded with privacy settings enabled and osm.org api produces non-standard gpx files.

The solution here would be to recognize these segments (perhaps a segment with no name would do fine) and render it as free points, not a continuous segment. I will have a look if our infrastructure supports it.

**Comment by denizzzka** [comment]
1. My tracks uploaded by any way in any mode to OSM site are shown in Merkaator as on above pictures.
2. In other programs everything works.

**Comment by Krakonos** [comment]
And do you upload your tracks with privacy settings on? If so, I believe I have identified the problem and will work on the fix. If not, we'd need to check the original files and see if osm.org did some other mangling.

I will probably have a fix ready in a few days and will ask you to test on your tracks.

**Comment by Krakonos** [comment]
Hi! I have opened PR #196 . Can you test if it does what you'd expect? The implementation is just a draft of the detection would look like, I need to improve that, but the result will be as in the branch.

**Comment by Krakonos** [comment]
I have updated the PR to a merge-able state. Please let me know when you are able to test it.

**Comment by denizzzka** [comment]
Now it just ommits these tracks. This is same place of map as above:

![image](https://user-images.githubusercontent.com/974632/62833812-e53e4a80-bc6e-11e9-965b-4ad922310f76.png)

**Comment by Krakonos** [comment]
Hmm, can you verify that you downloaded the points in the whole area? I'm getting different results (see attachment) that do contain the nodes in question. I'm testing on 6167922741e1df708cc7349384727af6f3f28d83 .

![2019-08-13-092332_2560x1403_scrot](https://user-images.githubusercontent.com/138209/62922738-69e2b300-bdac-11e9-88a4-2144742a1a22.png)

**Comment by denizzzka** [comment]
Yes, some have displayed, but not all.

It’s inconvenient to zoom out so far to download at least some tracks...

**Comment by Krakonos** [comment]
Hmm, so for example this URL:
https://www.openstreetmap.org/#map=19/56.17258/92.97606
(clicking edit -> remote; then in Merkaartor "Download", keeping "current view" option and checking "download gps tracks"). Looks like this:

![2019-08-13-115750_2560x1403_scrot](https://user-images.githubusercontent.com/138209/62933132-d61be180-bdc1-11e9-85a2-9e68d02a763d.png)

Compared to current master:

![2019-08-13-120138_2560x1403_scrot](https://user-images.githubusercontent.com/138209/62933292-298e2f80-bdc2-11e9-9bda-eddae165ff7f.png)

I do believe all the trackpoints are there. This coincidentally is the area where you are missing the points, but I can't reproduce the problem.

**Comment by denizzzka** [comment]
> https://www.openstreetmap.org/#map=19/56.17258/92.97606

OsmLink: "Invalid URL: "
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2279, resource id: 8393437, major code: 40 (TranslateCoords), minor code: 0

**Comment by denizzzka** [comment]
Here is should be displayed a track
![image](https://user-images.githubusercontent.com/974632/62952749-77cd1e00-be16-11e9-9814-196a8e3a3eb0.png)

according to:
![image](https://user-images.githubusercontent.com/974632/62952790-874c6700-be16-11e9-8985-9e3f275f05eb.png)

**Comment by Krakonos** [comment]
Yep, and those points are there, even including those off path, on the same spot as the screenshot from osm.org:

![2019-08-14-080733_2560x1403_scrot](https://user-images.githubusercontent.com/138209/62998082-ad035b80-be6a-11e9-9649-2c2e7eb982c0.png)

I can reliably get all those points into the view, both when zoomed completely in, or zoomed out to the whole area in question. Can you provide me with instructions how to reproduce it? Because it seems I'm unable to. I have already tried on multiple machines and platforms as well.

**Comment by denizzzka** [comment]
I just opened Merkaartor, slightly zoomed out from your latest screenshot and then downloaded map part with GPS tracks checkbox enabled.

**Comment by Krakonos** [comment]
Nope, I cannot reproduce it. Sorry. A few extra ideas comes to mind:

1) Verify you have a layer called "Anonymized trackpoints". If so, try toggling visibility to see if it contains some points; you can also right-click the layer and select "zoom" to zoom in on all the objects. This will show us if the problem is in downloading or rendering.

2) Try to switch to a different one (Tools -> Style)? I'm using MapnikPlus, but all of the default ones should work. It might be possible you have some customization or there is something else at play.

3) As a last resort, you can try to reset your configuration ((re)move ~/.merkaartor from your home). Please backup it before doing so, if it turns out it fixes the problem, we need to examine the configuration.

**Comment by denizzzka** [comment]
1. enabled
2. same as you use
3. tried without successful result

Maybe there is some library for reading GPX files or some library for coordinate conversion or something else that may be outdated and needs to be updated? Because besides of Merkaartor source code all other libraries I have from the Debian tree.

**Comment by Krakonos** [comment]
Hi!

I just tried on a fresh install of debian 10 + libs from Merkaartor readme and I cannot reproduce this issue on this branch. I believe the original issue is fixed and you are having a separate issue. Could you perhaps try to reproduce the same on a fresh install and report if the problem persists? Perhaps we can get to the bottom of it. I'm willing to install an OS into a vm to reproduce the problem, if we can figure out what the combination is.

Anyway, please create a followup issue if you have any extra information.

Thanks!

**Comment by denizzzka** [comment]
>  fresh install of debian 10 + libs from Merkaartor

Can you provide version? I am on `0.18.3+ds-5+b1`

**Comment by Krakonos** [comment]
None, compiled from source (from PR #196 ), as the original version has the aforementioned bug. The PR fixes the drawing issue of anonymized points, but I cannot reproduce the completely missing points you reported.

I used debian 10 as a base to check if some libraries could cause issues.

**Comment by denizzzka** [comment]
Updated everything including Debian version, isn't helped

**Comment by Krakonos** [comment]
Can you perhaps try out on a fresh debian install in a VM and provide the VM image showing the problem? Would help a lot in debugging, otherwise I don't have any ideas what might be the cause without actually being able to reproduce it somewhere.

I can arrange you some storage for the VM image, send me a private message if you need it.

Thanks.
