### ISSUE TITLE
0.18.3 not importing shapefiles on Windows

### ISSUE THREAD

**Issue by Cozmo5** [openstreetmap/merkaartor#182]
Verison .18.3 on Windows 10

I'm trying to import an ESRI shape file that includes the .cpg,.dbf,.prj,.qpg,.shp,.and .shx files but am seeing the following errors:

Importing file "C:/Documents/sample/sample.shp" using native parsers.
File type not recognized. If this file was recognized by previous versions, use Import GDAL function.
Importing file "C:/Documents/sample/sample.shp" using GDAL.
Created layer "sample.shp"
Layers # 1
"+proj=longlat +datum=NAD83 +no_defs"
ERROR 6: Unable to load PROJ.4 library (libproj-0.dll), creation of
OGRCoordinateTransformation failed.

Importing file "C:/Documents/sample/sample.shp" using GDAL.
Created layer "sample.shp"
Layers # 1
"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +to_meter=0.017453292519943295769236907684886"
ERROR 6: Unable to load PROJ.4 library (libproj-0.dll), creation of
OGRCoordinateTransformation failed.

**Comment by Krakonos** [comment]
Is that from the official installer? I will have a look, probably a missing library.

**Comment by Krakonos** [comment]
You can try the latest Windows nightly build:

https://bintray.com/krakonos/nightly/Merkaartor/0.18.3-97-g4389ed56

It seems to load proj.4 library fine, however, there seem to be other issues and GDAL crashes during import of some shapefiles I have at hand.

**Comment by Krakonos** [comment]
Btw. I have changed the title so it reflects it's a windows-only issue. On linux, it works much better and more reliably.

**Comment by mwoehlke-kitware** [comment]
It's not Windows-only. I can't open shapefiles (e.g. [this](https://gisdata-pwcgov.opendata.arcgis.com/datasets/roads)) with the Fedora package either, at least not with regular import (GDAL import works). Also, this is with merkaartor-0.18.4-3.fc32.x86_64.

**Comment by Krakonos** [comment]
I have analyzed and fixed some GDAL issues in PR #235. Bundled in the repository are some shapefiles that are used in tests (make test when using cmake).

Import of the dataset mentioned by @mwoehlke-kitware works well, though the rendering speed afterwards is not awesome - but that is a different story.

**Comment by Krakonos** [comment]
After a da790176daf75a83a803774c958d51928fb1c93f , it works on windows as well (GDAL uses a separate proj context and needed to set the path appropriately too).

**Comment by Krakonos** [comment]
Just tested CI-generated installer from https://cloudsmith.io/~merkaartor/repos/merkaartor-nightly/packages/?q=version%3A0.18.4-175-ga0dff160 , it fixes the issue.
