### ISSUE TITLE
The strange naming convention for variables has been seen elsewhere

### ISSUE THREAD

**Issue by PeterMortensen** [openstreetmap/merkaartor#184]
In [HACKING.md](https://github.com/openstreetmap/merkaartor/blob/master/HACKING.md) you ask:

> "... the strange naming convention for variables. They are often prefixed with a definite or indefinite article, like aLayer and theLayer. ... I know nothing about it, so if you have seen it elsewhere, let me know!"

One example was in the commercial C++ framework *Think Class Library* (TCL), bundled with the  [THINK&nbsp;C](https://en.wikipedia.org/wiki/THINK_C) compiler. TCL was similar to Qt, for creating GUI-based applications, etc. This was in the early 1990s for MacOS (before both Mac&nbsp;OS&nbsp;X and PowerPC).

It used the definite or indefinite article prefix, the indefinite for *parameter names* of a function and the definite for *scalar member variables* (not class instances). It also used the *"its"* prefix for members that were class instances (this was before references in C++, so all access to class instances were through pointers). If I remember correctly, this was to indicate ownership (responsibility for destruction, etc.). 

The TCL framework also had the convention of "I" for second-level initialisation of objects after creation (possibly due to limitations in the compiler support of C++ features - I don't remember).

<sub>(Note: I don't know if this is an example of Hungarian notation or not, but people have been severely burned by the *misunderstanding*/*misapplication* of Hungarian notation by the Windows documentation team. And by extension, most people now have this misunderstanding of Hungarian notation.</sub> 

<sub>See e.g. 04 mins 00 secs - 06 mins 35 secs in *[Triangulation 277](http://www.podtrac.com/pts/redirect.mp3/cdn.twit.tv/audio/tri/tri0277/tri0277.mp3)* and *[Making Wrong Code Look Wrong](https://www.joelonsoftware.com/2005/05/11/making-wrong-code-look-wrong/)*, near "a defense of a certain type of Hungarian Notation" for what Hungarian notation really is. The author of Hungarian notation pointed this out several times in the original paper, but still people at Microsoft grossly misunderstood and misapplied it.)</sub>

**Comment by Krakonos** [comment]
Thanks, that clears it a bit. If you don't mind, I have copy-pasted your explanation to the hacking.md, see PR #200 and comment if you are OK with that (or want to change it a bit).

**Comment by PeterMortensen** [comment]
I will do it within 24 hours.

**Comment by Krakonos** [comment]
Ping. Did you have time to go over it?

**Comment by Krakonos** [comment]
I went ahead and merged that, please open PR or other issues if you have any comments and we can fine tune that.

Thanks again for your insight!
