### ISSUE TITLE
Update Proj.4 API to version 6.0

### ISSUE THREAD

**Issue by Krakonos** [openstreetmap/merkaartor#193]
Currently, we use the deprecated API (see #178 ), which will be removed early 2020. We need to adopt the new API before that. Some initial work has already been done by @z3ntu  in #178.

**Comment by a17r** [comment]
> PROJ 7 will be last major release version that includes the proj_api.h header. The functionality in proj_api.h is deprecated and only supported in maintenance mode.

From 7.0.0 release notes: https://proj.org/news.html#id58

**Comment by Krakonos** [comment]
Thanks for the heads up. This is becoming urgent. If anyone a bit more knowledgeable about proj.4 would like to take a look, PR would be appreciated. Otherwise, I'll tackle it somehow.

**Comment by sebastic** [comment]
The first PROJ 8.0.0 release candidate has been released which removes `proj_api.h`.

**Comment by Krakonos** [comment]
Thanks for the heads up. I have migrated to the version 6 API in branch https://github.com/openstreetmap/merkaartor/tree/proj-remove-legacy-api . Tested against PROJ 6.3.2. I wrote a few tests (compiled on cmake only), to make sure it works the same as the original API, though I did gather only a few datapoints.

Though non-Mercator projections seem to be rendered differently for OSM layers and TMS layers, this does not apper to be a regression, as the 0.18.4 exhibits exactly the same behavior.

**Comment by Krakonos** [comment]
The PR above is more or less ready for this issue.

I started some work on correct projection usage in image map layers, but that will be a separate branch/PR. I have TMS more or less ready, but there are some precision issues and they are hard to track down - there are way too many intertwined transformations along the way that may need to be cleaned up first.

**Comment by kkofler** [comment]
For any packagers reading this, here's a version of the patch (derived from the pull request #233 linked above) that works with the 0.18.4 release:
https://src.fedoraproject.org/rpms/merkaartor/raw/f529682d49b0a8433a523bc257a9d05323c2489b/f/merkaartor-0.18.4-proj-remove-legacy-api.patch
(I ripped out the Travis parts that do not apply and massaged the `CHANGELOG` so that the hackish version parsing script does not choke on it.)

**Comment by Krakonos** [comment]
After some testing, it appears none of the issues are new. The PR is merged and master branch builds with newer proj. Any further issues need to be reported separately.

**Comment by sebastic** [comment]
There is no release date for the 0.19.0 milestone, when do you expect that?

**Comment by Krakonos** [comment]
I'm currently working on PR #234, testing mostly windows build. Once that is ready, I expect to tag a 0.19.0 release candidate to test all of that out. I'd say a week is possible, two weeks are realistic.
