### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by embeddedmz** [openstreetmap/merkaartor#203]
I can't build the application under Ubuntu 18.04.3 LTS: undefined reference to « Merkaartor::RemoteControlServer::staticMetaObject »

I tried also to build the 0.18.4 branch. Same link issue:

> [100%] Linking CXX executable merkaartor
> CMakeFiles/merkaartor.dir/src/MainWindow.cpp.o : Dans la fonction « MainWindow::delayedInit() » :
> MainWindow.cpp:(.text+0x2752) : référence indéfinie vers « Merkaartor::RemoteControlServer::RemoteControlServer(QObject*) »
> MainWindow.cpp:(.text+0x276d) : référence indéfinie vers « Merkaartor::RemoteControlServer::requestReceived(QString) »
> MainWindow.cpp:(.text+0x27d5) : référence indéfinie vers « Merkaartor::RemoteControlServer::listen() »
> CMakeFiles/merkaartor.dir/src/MainWindow.cpp.o : Dans la fonction « MainWindow::preferencesChanged(PreferencesDialog*) » :
> MainWindow.cpp:(.text+0x1595e) : référence indéfinie vers « Merkaartor::RemoteControlServer::listen() »
> MainWindow.cpp:(.text+0x15974) : référence indéfinie vers « Merkaartor::RemoteControlServer::close() »
> CMakeFiles/merkaartor.dir/src/MainWindow.cpp.o : Dans la fonction « std::enable_if<QtPrivate::FunctionPointer<MainWindow::delayedInit()::{lambda(QString)#1}>::ArgumentCount==(-1), QMetaObject::Connection>::type QObject::connect<void (Merkaartor::RemoteControlServer::*)(QString), MainWindow::delayedInit()::{lambda(QString)#1}>(QtPrivate<void (Merkaartor::RemoteControlServer::*)(QString)>::Object const*, std::enable_if<QtPrivate::FunctionPointer<MainWindow::delayedInit()::{lambda(QString)#1}>::ArgumentCount==(-1), QMetaObject::Connection>::type, QObject const*, QtPrivate::FunctionPointer, Qt::ConnectionType) » :
> MainWindow.cpp:(.text+0x1fd72) : référence indéfinie vers « Merkaartor::RemoteControlServer::staticMetaObject »
> collect2: error: ld returned 1 exit status
> CMakeFiles/merkaartor.dir/build.make:3508: recipe for target 'merkaartor' failed
> make[2]: *** [merkaartor] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/merkaartor.dir/all' failed
> make[1]: *** [CMakeFiles/merkaartor.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by Krakonos** [comment]
Please follow the instructions in COMPILE.md. CMake build system is not production ready and contains more issues than this obvious one (just merged in PR that fixes it), for example there are plugins missing, version strings are messed up and possibly other issues.

Compiling using qmake should work fine.
