### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by ghost** [openstreetmap/merkaartor#213]
Please, setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

- AppImage Docs - https://docs.appimage.org/

### TODO

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by Krakonos** [comment]
Hi! There actually is a PR #173 implementing that. However, I believe that downloading the latest package is not a wise thing to do, unless we can authenticate it easily. There is a release version of the linuxdeployqt tool that we could store sha256 in repo and check that, though I haven't been able to test anything, as my system is apparently too new (and the linuxdeployqt did not run on it last time I checked). 

Feel free to contribute a PR that would add these features. I may or may not have time to look into it in the near future.

**Comment by stephan75** [comment]
Is Travis CI still used for merkaartor?

If not, close this issue?

**Comment by Krakonos** [comment]
Yes, it is. I'd like to eventually build some kind of independent linux package, but particularly appimage became difficult due to upgrade in the base linux distribution on travis (as appimage tooling above requires pretty ancient glibc versions, where new gdal, proj and cmake are not readily available).

**Comment by Krakonos** [comment]
AppImage is part of the current 0.20.0 release builds, built on github actions.
