### ISSUE TITLE
Can't open on Mac

### ISSUE THREAD

**Issue by apbarratt** [openstreetmap/merkaartor#238]
Sorry for not having much helpful information.  I'm new to merkaartor today and just downloaded the Mac version from the main download page.  I chose Merkaartor 0.18.4: Qt5.  (I have no idea what the Qt stuff really means to be honest).

I stuck it in my Applications folder and right clicked and Opened to get past the usual Mac security nonsense.  The app can be seen opening in the dock but freezes up seconds later with no UI loaded.  The Force Quit Applications dialogue shows it as `(not responding)`

I'm running Mac OS Big Sur (11.2.3) and a MacBook Pro with M1 chip (I would not be surprised if this is part of the problem, most apps run fine but more exotic things do sometimes struggle with it).

When I force close, Mac OS does give me a rather gigantic crash report to send to Apple, let me know if a copy of this might be useful to look at.  I'd have to check if it's got any private data in it but suspect that'd be unlikely so so be good to go :)

**Comment by Krakonos** [comment]
Hi!

thanks for the report. I did recently test Merkaartor on Big Sur and M1 silicon, though I'm not sure if I included 0.18.4. I'm currently in the process of testing and releasing a new release and I tested that. Seemed to work well, though I don't have Mac myself so I only had limited time to test it.

Would you mind testing the latest nightly build?

https://cloudsmith.io/~merkaartor/repos/merkaartor-nightly/packages/?q=version%3A0.18.4-175-ga0dff160

If that doesn't work, as much information would be appreciated, so please upload the bug report somewhere, or send it to krakonos@krakonos.org ; possibly encrypting it with my GPG key 0369C2556301FD917294E33EF0223ACB22EEAEEF if you suspect private information may be leaked there (I'm not sure what the report contains, but it will at least give out some information about file structure and such things; please review before sending anyway).

**Comment by alicera** [comment]
> thanks for the report. I did recently test Merkaartor on Big Sur and M1 silicon, though I'm not sure if I included 0.18.4. I'm currently in the process of testing and releasing a new release and I tested that. Seemed to work well, though I don't have Mac myself so I only had limited time to test it.
>I don't have Mac myself so I only had limited time to test it.
Does the travis-ci.org cant work？

travis-ci can generate a macos env and test it with my code. Is it correct？
I dont have the experince with travis ci.

**Comment by Krakonos** [comment]
Travis-ci can generate the installer (see the link above), but it currently can not test much on the platform. Testing issues like this is even more problematic, as the symptoms show some UI interaction and travis runs in headless mode.

**Comment by KAMiKAZOW** [comment]
0.19-rc1 opens just fine on Big Sur Intel. You should replace the Mac download link with that. 0.18.x just doesn't work at all.

**Comment by Krakonos** [comment]
@apbarratt Can you validate the final 0.19.0 works for you? I did some basic testing on Big Sur M1 and it works fine. @KAMiKAZOW  tested on Intel (though only the rc1).

**Comment by Krakonos** [comment]
Due to no additional comments I consider the issue solved my lastest release. Please open a new issue if new problems arise with the 0.19.0 release.
