### ISSUE TITLE
it is impossible to select the localization language

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/merkaartor#261]
it is impossible to select the localization language
merkaartor-0.19.0-1-win64.exe

**Comment by Krakonos** [comment]
Will check, could be a problem with the installer.

**Comment by Krakonos** [comment]
Fixed in PR #265 . As a workaround, you can move the translation files from (install dir)/share/merkaartor/translations into (install dir)/bin/translations .

**Comment by Krakonos** [comment]
PR #265 merged, you can find updated binaries here: 
https://cloudsmith.io/~merkaartor/repos/merkaartor-nightly/packages/?q=version%3A0.19.0-10-g0ec4e27b
