### ISSUE TITLE
Zooming after closing a gps track layer results in a immediate crash.

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#3]
Download data and gps tracks.

Zooming after closing a gps track layer results in a immediate crash.
Mooving after closing a gps track layer results in a non-immediate crash.

Closing the downloaded data layer and zooming/moving after it causes crash.

This is present in 0.18.0 and current master branch. (debian)
This is something that has worked correctly in the past but I have no idea when it last worked correctly.

**Comment by Krakonos** [comment]
It seems the layer is deleted, but the nodes and possibly other stuff are not. The commit b9827c3ea4a556b7d291da64e39fe51e2bf7c28f fixes that partially: Merkaartor no longer crashes, but the features remain on the map. Needs more work.

**Comment by Krakonos** [comment]
Fixed in 4daa4e949140226ed33c83d5ed3fb19d21dba73a. If you find some issues with it, please, report them.
