### ISSUE TITLE
Endless loop with networking debug string.

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#44]
The following message is printed to console several times per second:
"Authentication required and provided."

String location: MerkaartorPreferences.cpp

**Comment by Krakonos** [comment]
Strange. I can see it, and will take a look.

**Comment by Krakonos** [comment]
I see, it happens if you have wrong password prefilled. Dumb. This is part of the code that needs some serious rewrite, but I will make a fix for this.

**Comment by RM87** [comment]
That it was.

**Comment by Krakonos** [comment]
This fixes it for me.
