### ISSUE TITLE
Build fails with GDAL 2.0

### ISSUE THREAD

**Issue by volter** [openstreetmap/merkaartor#49]
The GDAL 2.0 API change causes Merkaartor builds to fail. Please see the build log below for details!

http://trac.osgeo.org/gdal/wiki/GDAL20Changes

https://copr-be.cloud.fedoraproject.org/results/volter/gdal-2.0/fedora-rawhide-x86_64/merkaartor-0.18.1-13.fc23/build.log.gz

**Comment by Beowulf0** [comment]
I can confirm this issue.

**Comment by Krakonos** [comment]
It seems the GDAL interface is a bit broken anyway, and uses some deprecated parts. I'll try to fix it.

**Comment by Krakonos** [comment]
I've pushed a gdal-2 branch, that should fix it.

Beware that the GDAL export code probably does not work, as it looks unfinished.

**Comment by Krakonos** [comment]
I've merged the gdal-2 fix into master, the bug is fixed.

**Comment by Beowulf0** [comment]
This fixes the issue for me, thanks.
