### ISSUE TITLE
SpatialiteBackend relies on deprecated spatalite_init() method

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/merkaartor#50]
All software built on top of libspatialite needs to stop using the deprecated spatialite_init() method in favour of its thread-safe variant spatialite_init_ex().

Recently libspatialite (4.1.1) was rebuilt in Debian with PROJ.4 4.9.1 whose new threading engine causes segfaults in libspatialite when the deprecated spatialite_init() method is used (see for example Debian Bug [#785091](https://bugs.debian.org/785091) & [#790224](https://bugs.debian.org/785091))

Please refer to the [How to correctly initialize SQLite/SpatiaLite therad safe connections](https://groups.google.com/d/msg/spatialite-users/83SOajOJ2JU/sgi5fuYAVVkJ) thread on the spatialite-users list for details of the new spatialite_init_ex() API.

Some more information is available in the threads on [gdal-dev](http://lists.osgeo.org/pipermail/gdal-dev/2015-May/041806.html) & [qgis-developer](http://lists.osgeo.org/pipermail/qgis-developer/2015-May/037824.html).

**Comment by Krakonos** [comment]
Thanks for reporting. The SpatialiteBackend is not used by default, and currently no a priority. I'll take a look, to see if it even works with older versions of libspatialite and proj4, I suspect it might not.

**Comment by sebastic** [comment]
On 07/14/2015 09:33 PM, Ladislav Láska wrote:
> The SpatialiteBackend is not used by default, and currently no a priority.

The merkaartor Debian package is built with SPATIALITE=1 causing it to
be affected by the segfaults caused by the deprecated spatialite_init()
method.

> I'll take a look, to see if it even works with older versions of libspatialite and proj4, I suspect it might not.

Thanks, I hopeful the recent revival of merkaartor development will
resolve this issue eventually. I'm looking forward to seeing a different
version in the archive after you release 0.19.

**Comment by Krakonos** [comment]
Good point. I've changed the initialization sequence in the spatialite branch. Unfortunately, it looks like even with SPATIALITE=1 the backend is not used, and even lacks some methods the code needs and MemoryBackend has. I guess it's been dead for a long time, and the patches from debian repository (looked at the testing version) don't seem to do anything about it.

The only place where spatialite is used is the spatialite plugin, which needs to be invoked in order to initialize spatialite. I've fixed that too.

Could you please test, if it's a real problem? I only have an old wheezy machine at my hand.

**Comment by sebastic** [comment]
On 07/18/2015 11:57 PM, Ladislav Láska wrote:
> Good point. I've changed the initialization sequence in the spatialite branch. Unfortunately, it looks like even with SPATIALITE=1 the backend is not used, and even lacks some methods the code needs and MemoryBackend has. I guess it's been dead for a long time, and the patches from debian repository (looked at the testing version) don't seem to do anything about it.
> 
> The only place where spatialite is used is the spatialite plugin, which needs to be invoked in order to initialize spatialite. I've fixed that too.

Are your changes available somewhere?

> Could you please test, if it's a real problem? I only have an old wheezy machine at my hand.

Starting merkaartor with a spatialite database as its argument is
sufficient to trigger a segfault. gdb reports that it's actually via
libgdal, not libspatialite directly:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6ae3851 in OGRSpatialReference::Dereference() () from
/usr/lib/libgdal.so.1

Once GDAL is updated to 1.11.2 it will stop using the deprecated
spatialite_init() method.

I can't seem to find the path to any of the merkaartor code calling
spatialite_init() so I tend agree that it looks like dead code.

**Comment by Krakonos** [comment]
They have both separate branches, as I expect some minor incompatibilities/problems:

Tha patches for spatialite are here: https://github.com/openstreetmap/merkaartor/tree/spatialite
The GDAL-2: https://github.com/openstreetmap/merkaartor/tree/gdal-2

I guess the GDAL-2.0.0 might use the new spatialite_init_ex method? I haven't checked. If it isn't, there probably is no help besides waiting for GDAL guys to fix it.

**Comment by sebastic** [comment]
On 07/19/2015 10:36 AM, Ladislav Láska wrote:
> They have both separate branches, as I expect some minor incompatibilities/problems:
> 
> Tha patches for spatialite are here: https://github.com/openstreetmap/merkaartor/tree/spatialite
> The GDAL-2: https://github.com/openstreetmap/merkaartor/tree/gdal-2

Thanks, both branches look good. We still need to transition to GDAL
1.11.2 in Debian (currently blocked by the uncoordinated mapnik 3.0
transition) before we can start preparing for the GDAL 2.0 transition.
It's good to know support merkaartor has support in the works.

> I guess the GDAL-2.0.0 might use the new spatialite_init_ex method? I haven't checked. If it isn't, there probably is no help besides waiting for GDAL guys to fix it.

GDAL >= 1.11.0 will use the new spatialite_init_ex() method for
SpatiaLite >= 4.1.2. You may want to adopt the same conditional to keep
supporting older spatialite release (e.g. Debian stable ships with 4.1.1).

**Comment by Krakonos** [comment]
As far as I can tell, the 4.1.0 already contains the new API, and the spatialite stuff is not that great to support older releases -- if you really want to use spatialite, please, do it with a new version. Of course, the GDAL functionality will work with older spatialites, depending on the GDAL version.

I've merged both branches into master and consider it fixed.
