### ISSUE TITLE
version 0.18.2 refers to old openstreetbugs service

### ISSUE THREAD

**Issue by stephan75** [openstreetmap/merkaartor#52]
In menu "Layers" you can choose "Add OpenStreetBugs layer" ... then Merkaartor tries to download stuff from openstreebugs.schokokeks.org

I assume that this service is no longer available, OpenStreetBugs are deprecated due to
http://wiki.openstreetmap.org/wiki/Notes ... where we even have a new own API.

**Comment by Krakonos** [comment]
Thanks, I'll remove the reference and possibly add some feature to highlight features with actie notes.
