### ISSUE TITLE
0.18.2 displays Bad Request, when it should display the real problem (you're trying to download too large area)

### ISSUE THREAD

**Issue by l29ah** [openstreetmap/merkaartor#57]
When trying to download any maps.

**Comment by Krakonos** [comment]
Hi! Bad Request happens if the map you're trying to download is too large. That may be due to it's pure size, or number of nodes in that area. Try choosing smaller area at a time.

I agree that the message is a bit misleading, and I will update it for the next version, to say something informative.

**Comment by l29ah** [comment]
Okay, i got it. So the London download preset is quite useless?

**Comment by l29ah** [comment]
By the way, is there a way to disable the lots of red dots a map is covered with?

**Comment by Krakonos** [comment]
Yes, the preset is pretty useles. I will probably remove it, as I don't see any value in it anyway. Maybe set it up so it zooms the selection map to the place and let's you select details.

The dots show the area that is not fully downloaded. You can disable them in Show->Show downloaded areas.

**Comment by Krakonos** [comment]
Fixed in 50ce6947f511d9630b36f87209d0152ce8c33881.

**Comment by relishcolouredhat** [comment]
Bit of a noob here - but I think the closure was in error; fix seems to be unrelated?

**Comment by Krakonos** [comment]
You're right, I'm not sure what I was thinking about when I posted that.

**Comment by SinusPi** [comment]
I also am hitting the Bad Request, on 0.18.3-64, but with an area of *[bbox=-144.124378,-89.169522,518.050908,85.996991] (that's one roundabout in Scotland) which is definitely NOT too large.

**Comment by ioquatix** [comment]
i am also hitting this error for some reason. Downloading Christchurch, NZ.

**Comment by Krakonos** [comment]
Hmm. I kind of forgotten about this issue, sorry. 

@SinusPi : The bbox looks weird. Do you remember the exact roundabout? Can it be exactly on the prime meridian? Is it triggered from the dialog, using "download more", remote control or some other way?

@ioquatix : Whole christchurch? That seems to be too large area. Try smaller chunk, it should work. I'll update the error message for next release.

**Comment by Krakonos** [comment]
Hi! In commit df8a089cddf8241d0c2a3139aebf3f8b2c9ea49b , I made a change to show the error message from server. In case the area is too large, it displays the correct problem (usually over 50000 nodes in the query).

@SinusPi As the issue you are having is mostly irrelevant to the error reporting, please fill a new issue with more info about that roundabout. Thanks!

**Comment by ioquatix** [comment]
Is there some way to incrementally download a larger region so as to avoid this error?
