### ISSUE TITLE
0.18.2: Preferences - Data ... XAPI URL informationfreeway.org is deprecated

### ISSUE THREAD

**Issue by stephan75** [openstreetmap/merkaartor#58]
![image](https://cloud.githubusercontent.com/assets/5250044/9021618/e538efaa-384b-11e5-9a8e-7e67c5b6242f.png)

If I am not wrong, the predefined URL leading to www.informationfreeway.org is outdated.

Maybe on http://wiki.openstreetmap.org/wiki/Xapi we have data sources more uptpdate.

**Comment by Krakonos** [comment]
Thanks, fixed in b5ac95051327fa145b343799d9a00e80e6020fc3.
