### ISSUE TITLE
I have 12 dirty objects, but can't upload them

### ISSUE THREAD

**Issue by l29ah** [openstreetmap/merkaartor#59]
The upload window suggests i have no edits: https://dump.bitcheese.net/files/evurapi/screenshot-merkaartor-dirty.png

**Comment by Krakonos** [comment]
There are two possibilities: the objects really did not change (moved them somewhere and back, not very likely), or they are on part of a map you don't have fully downloaded, in this case, this bug manifests itself. See bug #8. I'll take a look when I'm back from china.

**Comment by l29ah** [comment]
Well, nope: those changes are all new objects, they aren't uploaded yet and are put on a fully downloaded part of the map.

**Comment by Krakonos** [comment]
OK, could you tell me how to reproduce the problem, or send me a saved file (mdc) that has this issue? I'll take a look, but I haven't been able to reproduce it so far.

**Comment by stephan75** [comment]
this issue seems to be no more valid? close?

**Comment by Krakonos** [comment]
Possibly. Since I have no new clues, I'll consider it as part of bug #8, as suggested above.
