### ISSUE TITLE
Download dialog causes problems if waiting some time in the dialog

### ISSUE THREAD

**Issue by M-Reimer** [openstreetmap/merkaartor#61]
With the latest GIT version (built as seen here: https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=merkaartor-git) I have the following problem:

If I open Merkaartor (empty drawing area) and choose to dowload a region, then the dialog starts with "Current view" for some reason. If I now just keep the dialog open for a few seconds, then I have the following:
![download1](https://cloud.githubusercontent.com/assets/3519517/9149972/7ce56b40-3dc3-11e5-98dc-6de6f831688a.jpg)

Without even clicking something, Merkaartor pops up the "Downloading" window and there it hangs until I click "Cancel". If I do so, I get back to the "Download" window and am able to select "From the map below":
![download2](https://cloud.githubusercontent.com/assets/3519517/9149975/a653b59a-3dc3-11e5-9d77-c11e285aa3c4.jpg)

If I now click "OK", then I see the "Downloading" window for some seconds:
![downloading](https://cloud.githubusercontent.com/assets/3519517/9149977/b34fc7f2-3dc3-11e5-9223-37590f31b078.jpg)

But then I don't get back to the Merkaartor main window, but Merkaartor pops up the "Download" dialog, again, wanting me to select which region I want to download. I can repeat this as often as I want. I never get a successful download and I never get back to the Merkaartor main window. If I, at some time, hit "Cancel" in the "Download" dialog, then Merkaartor ends this loop with:
![error](https://cloud.githubusercontent.com/assets/3519517/9149981/e2c2ea28-3dc3-11e5-9014-d8b8f6a80320.jpg)

The only way to get around this is to be fast enough. If I'm able to switch to "From the map below" and "OK" before this "empty Downloading window" pops up, then Merkaartor downloads just fine without any problems...

**Comment by Krakonos** [comment]
Fixed in f6100d8de8fa3188f77a69026e858cc3b716cee6. This issue only showed up in Qt5 version, Qt4 was not affected.
