### ISSUE TITLE
Encourage people to use edit descriptions.

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/merkaartor#71]
People using this editor very frequently leave default edit description unchanged (is it even possible to change it?). It is highly irritating and make much harder to guess character of edit (normal work, newbie, vandalism...)

See for example https://www.openstreetmap.org/changeset/33340815 with utterly useless "BBOX:19.87,50.08,19.94,50.11 ADD:2 UPD:1 DEL:0".

**Comment by matkoniecz** [comment]
In comparison - JOSM strongly encourages to give not only edit description but also to describe source. iD makes possible to leave edit description and makes clear how it should be used.

**Comment by Krakonos** [comment]
Yes, I already have a plan to remove the default (and useless) description. I don't have a plan to do anything more, but I'm open to suggestions.

**Comment by RM87** [comment]
Maybe adding a sentence to upload dialog in style of: "Try to answer the questions what you did, where and based on what." would help enough?

**Comment by Krakonos** [comment]
Done in 44cd9fa66870953977a50a1f11533d7661a259d4. I hope you'll like it.

**Comment by matkoniecz** [comment]
Thanks! It should work well.
