### ISSUE TITLE
Garbage in console while using merkaartor

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/merkaartor#74]
While using merkaartor (0.18.2) I am seeing a lot of garbage in console.
For example, with a simple start and close I can see:

```
$ merkaartor 

b

 b
p b
Àe




À*
@
 å
 å
0
 ã{



`s
`s
 
°È{
°»ê
 ²å
















@!Þ


queue full

queue full

queue full

queue full

queue full

queue full

queue full

queue full

queue full

queue full

queue full

queue full
°Àµ


 »·
Bing Zoom:  17
Bing Zoom:  17


p)²
Bing Zoom:  17
PP·
PP·
5¿
Bing Zoom:  17
¶
¶
#Ù
Bing Zoom:  17






0ϸ


ðÄÒ

ÐíÀ
ÐíÀ
ÐíÀ
@	ß
@	ß
 'ß



pCæ



¨â


ðõÒ




 iÀ



 úÆ




ðæã


p]Þ





À7Æ
0ËÞ
0ËÞ
°¥¸
иÜ
иÜ
 k²


P,Â
ÐÝ
ÐÝ

ð9Â
ð9Â
ð<Þ


PSÊ
ЩÝ
ЩÝ
5Ù
`
PñÛ
```

**Comment by Krakonos** [comment]
Strange, I have never seen it. Let's get some more information about it:

1) On which OS is this happening?
2) What console are you using?
3) If you're using linux, please, post your locales (here is a command to do it: env | egrep "(LANG|LC)" )
4) Does this happen with other Qt programs? Merkaartor uses mostly qDebug() to print it's output.

**Comment by naoliv** [comment]
1)  Debian sid, with kernel 4.2.3-2 (2015-10-14) x86_64
2) urxvt (rxvt-unicode-256color)
3)
```
$ env | egrep "(LANG|LC)"
LANGUAGE=pt_BR:pt:en
GDM_LANG=pt_BR.utf8
LANG=pt_BR.UTF-8

$ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=
```
With `LC_ALL=C` I see the same.
4) other QT programs aren't having this issue

**Comment by Krakonos** [comment]
Allright, I've started my debian box, and although 32bit, it has the same problem (a tiny bit better, some strings are actually there). I'll try to find a fix for it.

**Comment by Krakonos** [comment]
The commit 84ba608 fixes the problem for me. Could you confirm this?

**Comment by naoliv** [comment]
It fixes the garbages in console :+1:
