### ISSUE TITLE
Double loading the same file crashes

### ISSUE THREAD

**Issue by RM87** [openstreetmap/merkaartor#80]
[untitled.txt](https://github.com/openstreetmap/merkaartor/files/50077/untitled.txt) change to .mdc
Load a saved file where something has been done (few newly added nodes suffice). Load the same file again

Result:
pure virtual method called
terminate called without an active exception

qt4 or 5

**Comment by Krakonos** [comment]
Thanks, I was able to reproduce and commited a fix. Please, reopen this issue if it's not so.
