### ISSUE TITLE
Testing versions 0.18.2 from end January 2016: Translations not included?

### ISSUE THREAD

**Issue by stephan75** [openstreetmap/merkaartor#89]
I downloaded and installed the 64bit testing version for Windows linked in the merkaartor mailinglist in end of January 2016.

Switching language to German in preferences fails!

Are translation files included in testing builds?
That would be nice because I need some "explanation" for certain strings to translate via transifex.

PS: Ladislav: when looking for more support for betatesting or translations, I recommend to do a posting in the OSM diaries at http://www.openstreetmap.org/diary ... Maybe you have your OSM account for that?

I tried some efforts via the OSM forum at http://forum.openstreetmap.org/viewforum.php?id=54 ... but no feedback so far.
Due to my many accounts in the OSM universe, I am not willing once more to participate in the merkaartor mailinglist, sorry.

EDIT:
... @Krakonos : or what about giving a hint about the recent testing versions at the main screen of http://merkaartor.be

**Comment by Krakonos** [comment]
Allright, I finally got to automate the builds and fixed this problem along with it. Since 0.18.2-89 the build will contain all the translations from git. 

The nightly builds will be available at (the build usually takes ~30 minutes for 64bit and another 30 for 32bit version, so be patient): 
https://bintray.com/krakonos/nightly/Merkaartor/view#files

I will update the web and docs once I do some more testing a perhaps polishing.

As for the testing & translations, I'm considering writing a few lines to the osm weekly authors. With the automated testing builds, I will also update the web page to include up to date links and stuff.

**Comment by stephan75** [comment]
Ladislav, many thanks for your efforts so far!!!

With new nightly version merkaartor-0.18.2-100-g03a6960-64bit.exe I can see that translation files are included, there are 177 files in C:\Program Files\Merkaartor\translations,

but when switching language from English to German (or French or Spanish), and after restarting Merkaartor, I still have English program texts ...

Can you switch to any other language succesfully?

**Comment by Krakonos** [comment]
How do you change language? I can change it in Preferences -> Locale, it switches fine. I will check later if it's persistent after restart, but I think it is and worked fine. At least it works for Czech, that is what I tested.

Or do you change language some other way, perhaps via some windows interface? I haven't tested this at all, as I don't have any non-english windows available.

**Comment by Krakonos** [comment]
I have tested again and switching works with all languages (I tried a few, including German). I'll try to find some way to do a detection and let you know.

**Comment by stephan75** [comment]
I am on a quite fresh installed Windows 10 in 64bit version. And I also tried several versions of Merkaators installers, 32 or 64 bit ... no difference.

freshest installer I tried is merkaartor-0.18.2-116-gc986345-32bit.exe from today.

Switching language is done like you wrote: Preference, Locale, check "Use language", switch to German, choose the applyy button down there, and it seems that at least the dialog buttons from Qt framework do a language switching, I mean those og OK, Cancel, Apply.

But all other menu text items in the whole program stay in English.

Console output from Windows10:

****  "2016-06-01T14:13:15"  -- Starting  "Merkaartor 0.18.2.116"
------- "using Qt version 5.6.0 (built with 5.6.0)"
------- "using PROJ4 version 4.9.2"
------- "using GDAL version 2.0.2"
------- with arguments:  ("C:\\Program Files (x86)\\Merkaartor\\merkaartor.exe")
PluginsDir: "C:/Program Files (x86)/Merkaartor/plugins"
Loading plugins from directory  "plugins"
Loading plugins from directory  "background"
  Loading "libMGdalBackgroundPlugin.dll.a" as plugin.
  Not a plugin:  "libMGdalBackgroundPlugin.dll.a" .
  Loading "libMGeoTiffBackgroundPlugin.dll.a" as plugin.
  Not a plugin:  "libMGeoTiffBackgroundPlugin.dll.a" .
  Loading "libMMsBingMapBackgroundPlugin.dll.a" as plugin.
  Not a plugin:  "libMMsBingMapBackgroundPlugin.dll.a" .
  Loading "libMWalkingPapersBackgroundPlugin.dll.a" as plugin.
  Not a plugin:  "libMWalkingPapersBackgroundPlugin.dll.a" .
  Loading "MGdalBackgroundPlugin.dll" as plugin.
loadProjection  "C:/Users/Kainer/.merkaartor/Projections.xml"
loadProjection  "C:/Program Files (x86)/Merkaartor/share/Projections.xml"
loadProjection  ":/Projections.xml"
loadFiltersFromFile  "C:/Users/Kainer/.merkaartor/Filters.xml"
loadFiltersFromFile  "C:/Program Files (x86)/Merkaartor/share/Filters.xml"
loadFiltersFromFile  ":/Filters.xml"
Requesting preferences from OSM server.
  Plugin loaded:  "MGdalBackgroundPlugin.dll" .
  Loading "MGeoTiffBackgroundPlugin.dll" as plugin.
  Plugin loaded:  "MGeoTiffBackgroundPlugin.dll" .
  Loading "MMsBingMapBackgroundPlugin.dll" as plugin.
  Plugin loaded:  "MMsBingMapBackgroundPlugin.dll" .
  Loading "MWalkingPapersBackgroundPlugin.dll" as plugin.
  Plugin loaded:  "MWalkingPapersBackgroundPlugin.dll" .
libpng warning: iCCP: too many profiles
libpng warning: iCCP: too many profiles
Created layer "Map - None"

-----------------

Do you have any clue?

Or can it be helpful to ask for more testing by more OSM users via a posting in high traffic OSM channels like the German OSM forum?

**Comment by Krakonos** [comment]
I'll do a bit more testing. There is some path selection going on, and I expect this to be a problem. I'll boot up Windows, there is still some testing to be done related to bug #99 .

I'll add some printouts in the language selection, so we get a better ideas on what's going on there.

**Comment by Krakonos** [comment]
One more thing: when you switch language and nothing happens, an error might show up in the main window status bar. Does the language code/name in there look right?

**Comment by stephan75** [comment]
> One more thing: when you switch language and nothing happens, an error might show up in the main window status bar. Does the language code/name in there look right?

Ohhh ... I was not able to see that status line because: When choosing the maximize feature of Merkaartor's main Window, that status line is hidden by the Windows10 task bar!!

So when minimizing the window manually, I can see now an error message, see the picture:

![image](https://cloud.githubusercontent.com/assets/5250044/15714327/689f0dca-281a-11e6-8311-574e988dd331.png)

**Comment by Krakonos** [comment]
More bugs, great! Thanks, this looks good. Could you take a look if your user can open the file translations/merkaartor_de.qm?

**Comment by stephan75** [comment]
There is no such file.

I will post teh content of translation folder:

 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 2612-C44A

 Verzeichnis von c:\Program Files (x86)\Merkaartor\translations

01.06.2016  14:11    <DIR>          .
01.06.2016  14:11    <DIR>          ..
01.06.2016  11:27             6.662 qmlviewer_cs.qm
01.06.2016  11:27                16 qmlviewer_en.qm
01.06.2016  11:27             6.782 qmlviewer_fi.qm
01.06.2016  11:27             6.976 qmlviewer_fr.qm
01.06.2016  11:27             6.154 qmlviewer_he.qm
01.06.2016  11:27             6.641 qmlviewer_hu.qm
01.06.2016  11:27             5.917 qmlviewer_ja.qm
01.06.2016  11:27             5.731 qmlviewer_ko.qm
01.06.2016  11:27             6.623 qmlviewer_ru.qm
01.06.2016  11:27             6.510 qmlviewer_sk.qm
01.06.2016  11:27             6.627 qmlviewer_uk.qm
01.06.2016  11:27           174.279 qtbase_ca.qm
01.06.2016  11:27           158.455 qtbase_cs.qm
01.06.2016  11:27           172.854 qtbase_de.qm
01.06.2016  11:27                16 qtbase_en.qm
01.06.2016  11:27           160.704 qtbase_fi.qm
01.06.2016  11:27           166.157 qtbase_fr.qm
01.06.2016  11:27           139.222 qtbase_he.qm
01.06.2016  11:27            91.101 qtbase_hu.qm
01.06.2016  11:27           154.226 qtbase_it.qm
01.06.2016  11:27           129.904 qtbase_ja.qm
01.06.2016  11:27           124.101 qtbase_ko.qm
01.06.2016  11:27           153.598 qtbase_lv.qm
01.06.2016  11:27           158.824 qtbase_ru.qm
01.06.2016  11:27           125.753 qtbase_sk.qm
01.06.2016  11:27           158.352 qtbase_uk.qm
01.06.2016  11:27            15.923 qtconfig_hu.qm
01.06.2016  11:27            24.560 qtconfig_ja.qm
01.06.2016  11:27            24.142 qtconfig_ko.qm
01.06.2016  11:27            21.453 qtconfig_pl.qm
01.06.2016  11:27            31.649 qtconfig_ru.qm
01.06.2016  11:27            31.344 qtconfig_sk.qm
01.06.2016  11:27            26.205 qtconfig_sl.qm
01.06.2016  11:27            21.475 qtconfig_uk.qm
01.06.2016  11:27            21.569 qtconfig_zh_CN.qm
01.06.2016  11:27            20.143 qtconfig_zh_TW.qm
01.06.2016  11:27            44.025 qtconnectivity_de.qm
01.06.2016  11:27                16 qtconnectivity_en.qm
01.06.2016  11:27            27.276 qtconnectivity_ko.qm
01.06.2016  11:27            39.706 qtconnectivity_ru.qm
01.06.2016  11:27            42.016 qtconnectivity_uk.qm
01.06.2016  11:27            64.621 qtdeclarative_de.qm
01.06.2016  11:27                16 qtdeclarative_en.qm
01.06.2016  11:27            53.415 qtdeclarative_fi.qm
01.06.2016  11:27            61.410 qtdeclarative_fr.qm
01.06.2016  11:27            45.294 qtdeclarative_ja.qm
01.06.2016  11:27            41.831 qtdeclarative_ko.qm
01.06.2016  11:27            53.930 qtdeclarative_lv.qm
01.06.2016  11:27            57.723 qtdeclarative_ru.qm
01.06.2016  11:27            48.647 qtdeclarative_sk.qm
01.06.2016  11:27            57.086 qtdeclarative_uk.qm
01.06.2016  11:27            24.184 qtlocation_de.qm
01.06.2016  11:27                16 qtlocation_en.qm
01.06.2016  11:27            22.148 qtlocation_fr.qm
01.06.2016  11:27            12.614 qtlocation_ko.qm
01.06.2016  11:27            21.715 qtlocation_ru.qm
01.06.2016  11:27            24.149 qtlocation_uk.qm
01.06.2016  11:27            18.098 qtmultimedia_ca.qm
01.06.2016  11:27            15.896 qtmultimedia_cs.qm
01.06.2016  11:27            17.246 qtmultimedia_de.qm
01.06.2016  11:27                16 qtmultimedia_en.qm
01.06.2016  11:27            15.332 qtmultimedia_fi.qm
01.06.2016  11:27            16.492 qtmultimedia_fr.qm
01.06.2016  11:27               864 qtmultimedia_hu.qm
01.06.2016  11:27            19.880 qtmultimedia_it.qm
01.06.2016  11:27            14.330 qtmultimedia_ja.qm
01.06.2016  11:27            12.445 qtmultimedia_ko.qm
01.06.2016  11:27            16.664 qtmultimedia_ru.qm
01.06.2016  11:27             9.886 qtmultimedia_sk.qm
01.06.2016  11:27            15.771 qtmultimedia_uk.qm
01.06.2016  11:27            38.648 qtquick1_ca.qm
01.06.2016  11:27            37.754 qtquick1_cs.qm
01.06.2016  11:27            42.246 qtquick1_de.qm
01.06.2016  11:27                16 qtquick1_en.qm
01.06.2016  11:27            34.478 qtquick1_fi.qm
01.06.2016  11:27            39.434 qtquick1_fr.qm
01.06.2016  11:27            32.178 qtquick1_he.qm
01.06.2016  11:27            17.742 qtquick1_hu.qm
01.06.2016  11:27            38.510 qtquick1_it.qm
01.06.2016  11:27            29.259 qtquick1_ja.qm
01.06.2016  11:27            27.395 qtquick1_ko.qm
01.06.2016  11:27            37.689 qtquick1_ru.qm
01.06.2016  11:27            36.580 qtquick1_sk.qm
01.06.2016  11:27            37.331 qtquick1_uk.qm
01.06.2016  11:27            12.677 qtquickcontrols2_uk.qm
01.06.2016  11:27             5.188 qtquickcontrols_de.qm
01.06.2016  11:27                16 qtquickcontrols_en.qm
01.06.2016  11:27             5.070 qtquickcontrols_fi.qm
01.06.2016  11:27             5.522 qtquickcontrols_fr.qm
01.06.2016  11:27             4.349 qtquickcontrols_ja.qm
01.06.2016  11:27             5.457 qtquickcontrols_ru.qm
01.06.2016  11:27             5.081 qtquickcontrols_uk.qm
01.06.2016  11:27             5.381 qtscript_ca.qm
01.06.2016  11:27             5.187 qtscript_cs.qm
01.06.2016  11:27             5.229 qtscript_de.qm
01.06.2016  11:27                16 qtscript_en.qm
01.06.2016  11:27             5.247 qtscript_fi.qm
01.06.2016  11:27             5.451 qtscript_fr.qm
01.06.2016  11:27             4.793 qtscript_he.qm
01.06.2016  11:27             4.257 qtscript_hu.qm
01.06.2016  11:27             5.373 qtscript_it.qm
01.06.2016  11:27             4.604 qtscript_ja.qm
01.06.2016  11:27             4.400 qtscript_ko.qm
01.06.2016  11:27             5.263 qtscript_lv.qm
01.06.2016  11:27             5.266 qtscript_ru.qm
01.06.2016  11:27             5.305 qtscript_sk.qm
01.06.2016  11:27             5.198 qtscript_uk.qm
01.06.2016  11:27             2.477 qtserialport_de.qm
01.06.2016  11:27                16 qtserialport_en.qm
01.06.2016  11:27             1.734 qtserialport_ja.qm
01.06.2016  11:27             3.138 qtserialport_ru.qm
01.06.2016  11:27             2.414 qtserialport_uk.qm
01.06.2016  11:27             9.184 qtwebengine_de.qm
01.06.2016  11:27                16 qtwebengine_en.qm
01.06.2016  11:27             8.525 qtwebengine_ru.qm
01.06.2016  11:27             8.447 qtwebengine_uk.qm
01.06.2016  11:27             9.539 qtwebsockets_de.qm
01.06.2016  11:27                16 qtwebsockets_en.qm
01.06.2016  11:27             9.629 qtwebsockets_fr.qm
01.06.2016  11:27             7.260 qtwebsockets_ja.qm
01.06.2016  11:27             8.800 qtwebsockets_ru.qm
01.06.2016  11:27             9.150 qtwebsockets_uk.qm
01.06.2016  11:27           113.183 qtxmlpatterns_ca.qm
01.06.2016  11:27           109.596 qtxmlpatterns_cs.qm
01.06.2016  11:27           117.121 qtxmlpatterns_de.qm
01.06.2016  11:27                16 qtxmlpatterns_en.qm
01.06.2016  11:27           115.899 qtxmlpatterns_fr.qm
01.06.2016  11:27           101.386 qtxmlpatterns_hu.qm
01.06.2016  11:27             5.097 qtxmlpatterns_it.qm
01.06.2016  11:27            81.624 qtxmlpatterns_ja.qm
01.06.2016  11:27            82.400 qtxmlpatterns_ko.qm
01.06.2016  11:27           100.259 qtxmlpatterns_ru.qm
01.06.2016  11:27            33.318 qtxmlpatterns_sk.qm
01.06.2016  11:27             7.932 qtxmlpatterns_uk.qm
01.06.2016  11:27            33.913 qt_ar.qm
01.06.2016  11:27               172 qt_ca.qm
01.06.2016  11:27               176 qt_cs.qm
01.06.2016  11:27           119.839 qt_da.qm
01.06.2016  11:27               172 qt_de.qm
01.06.2016  11:27                16 qt_en.qm
01.06.2016  11:27            82.414 qt_es.qm
01.06.2016  11:27           293.114 qt_fa.qm
01.06.2016  11:27               136 qt_fi.qm
01.06.2016  11:27               172 qt_fr.qm
01.06.2016  11:27           323.580 qt_gl.qm
01.06.2016  11:27            25.669 qt_he.qm
01.06.2016  11:27            11.007 qt_help_cs.qm
01.06.2016  11:27             8.785 qt_help_da.qm
01.06.2016  11:27            10.844 qt_help_de.qm
01.06.2016  11:27                16 qt_help_en.qm
01.06.2016  11:27            10.912 qt_help_fr.qm
01.06.2016  11:27            10.881 qt_help_gl.qm
01.06.2016  11:27             9.930 qt_help_hu.qm
01.06.2016  11:27            10.648 qt_help_it.qm
01.06.2016  11:27             7.910 qt_help_ja.qm
01.06.2016  11:27             8.146 qt_help_ko.qm
01.06.2016  11:27            10.492 qt_help_pl.qm
01.06.2016  11:27            10.444 qt_help_ru.qm
01.06.2016  11:27            10.378 qt_help_sk.qm
01.06.2016  11:27            10.356 qt_help_sl.qm
01.06.2016  11:27             9.740 qt_help_uk.qm
01.06.2016  11:27             6.434 qt_help_zh_CN.qm
01.06.2016  11:27             6.384 qt_help_zh_TW.qm
01.06.2016  11:27           272.165 qt_hu.qm
01.06.2016  11:27               172 qt_it.qm
01.06.2016  11:27               165 qt_ja.qm
01.06.2016  11:27               165 qt_ko.qm
01.06.2016  11:27           165.376 qt_lt.qm
01.06.2016  11:27           316.166 qt_pl.qm
01.06.2016  11:27            70.324 qt_pt.qm
01.06.2016  11:27               183 qt_ru.qm
01.06.2016  11:27               176 qt_sk.qm
01.06.2016  11:27           228.421 qt_sl.qm
01.06.2016  11:27            65.851 qt_sv.qm
01.06.2016  11:27               183 qt_uk.qm
01.06.2016  11:27           117.340 qt_zh_CN.qm
01.06.2016  11:27           117.256 qt_zh_TW.qm
             177 Datei(en),      7.183.795 Bytes
               2 Verzeichnis(se), 88.823.513.088 Bytes frei

And I was NOT able to save that listinh directly via dir > files.txt ... maybe no permission in Windows? I had to choose the path of my Windows desktop for saving that file.

**Comment by Krakonos** [comment]
Bummer! Now I know what's going on, though I'm not sure why it worked on my machine. Thanks, I'll get on that right now.

**Comment by stephan75** [comment]
Succeeeeeeeeeeeessss !!  :clap: :+1:

Many thanks!! And also the nightly-build-system seesm to be very good, it works with build 119 now.

PS: Still Merkaartor window gets too big when maximizing in Windows10 and Windows task bar is shown permanently ... open new issue?

**Comment by Krakonos** [comment]
Great! Yes, open a new issue for the window size please.
