### ISSUE TITLE
Improvements for Data Download Box

### ISSUE THREAD

**Issue by stephan75** [openstreetmap/merkaartor#91]
When choosing the map area from where to download raw OSM data, it seems that the OSM standard Mapnik map is displayed only with max. zoomlevel 18 ... correct?

At least **zoom level 19** should be possible.

and:

Let the user get more finetuning to the bounding box for data to be downloaded:

use right mousebutton for panning the map,
and left mousebutton to draw a bounding box for download.

(See how JOSM does this.)

**Comment by Krakonos** [comment]
The selection is done in 406c7283c3af5eb789d831fc6e63996fbad22815, the maximum zoom in cb3e10df78f410528dbf7292cce02c2a32ab51cb.

It could be improved, as all the floating point multiplication sometimes results in 1px different box than drawn, but that's good enough for now.
