### ISSUE TITLE
TMS: transparent tiles superpose when moving

### ISSUE THREAD

**Issue by Totor2015** [openstreetmap/merkaartor#93]
Old bug on all platforms.
When using a tileserver with transparent tiles (alpha layer in png), moving or zooming mixes new tiles with old ones.
See picture of result:
![merkaartor_transparent_tiles](https://cloud.githubusercontent.com/assets/17019119/13276200/c2c7818a-daf7-11e5-80e0-ef16ecb76b2b.png)

Test tile server:
```
<TmsServer minzoom="6" maxzoom="16" projection="EPSG:900913" tilesize="256" name="Transparent tiles" path="/hillshades/%1/%2/%3.png" address="osm.totor.ph" tmsorigin="true" /> 
```
location : 
```
<topright lon="124.5977829" lat="10.9166392"/><bottomleft lon="123.5956083" lat="10.1707275"/>
```

**Comment by Krakonos** [comment]
Great, this looks like *real* tms server. Could you post the URL to access it, so I can test it?

**Comment by Totor2015** [comment]
Its in the xml code:
Http://osm.totor.ph/hillshades/%1/%2/%3.png
It is only covering cebu island in the philippines
And needs the checkbox for the origin

**Comment by Krakonos** [comment]
Fixed in the current master, thanks for reporting!

**Comment by Totor2015** [comment]
Confirmed as fixed.
Thanks
