### ISSUE TITLE
0.18.2 ... no proper hint when a selected element belongs to a relation?

### ISSUE THREAD

**Issue by stephan75** [openstreetmap/merkaartor#97]
Either I am blind that I cannot see it, or haven't used a needed view option, or:

Merkaartor gives no proper hint when an element belongs to a relation.

Although I can see the green squares around each loaded relation which have a green-blue frame when a member element is selected, this seems not to be user-friendly enough.

Because what to do when an element belongs to really many relations?
Or relations are really big so that you don't have the green squares on scope?

So I ask:
Is it possible to implement a display of any parent relation like in Vespucci, iD or JOSM in text form and not only via graphical display?

**Comment by Krakonos** [comment]
Well, the relation work is pretty bad. Based on the description you can see green frame, this shows if you select Show -> Relations. That's sometimes useful, especially if you have a few relations, or just want to see what's in the are and where (I use it relations in the are don't have proper name=*).

In 0.18.3, there will be a feature where you can filter relations (in the Features dock) based on selection. That is, you select one or more objects, and only relations intersecting selection will be shown.

There is no fancy child/parent tree-view, as you'd expect. I plan to implement this in 0.19.0, together with a lot of other stuff, but it will take some time until I get to it.

**Comment by Krakonos** [comment]
Cleaning up the tasks. The filtering is implemented in 0.18.4. Advanced relations management might happen in 0.19.0 and is tracked as #137 .
