### ISSUE TITLE
Bing tiles not showing up on Windows 10

### ISSUE THREAD

**Issue by fusionstream** [openstreetmap/merkaartor#99]
So I don't know why no one has reported this yet but yea..

Bing tiles don't appear on Windows 10. They appear to download very fast but then nothing shows up.

Merkaartor 0.18.2 but it shows up as 0.18.1

**Comment by Krakonos** [comment]
I have no idea why. I tested on my Win10 and it worked fine. Could you retest with latest nightly builds?
You can find them here: https://bintray.com/krakonos/nightly/Merkaartor (I just set it up today, so report any issues you find)

**Comment by fusionstream** [comment]
Yep. Just tried it. Still got nothing. I do see the Bing watermark at the bottom right but everything else is white (with the red dotted thing for the osm layer). I'm not using my usual internet connection atm so the tiles seemed to "load" slower but when I get the time I will try it under the same conditions.  I'm using the Bing Maps plugin.

**Comment by Krakonos** [comment]
Great. Well, not that great :-). Could you run merkaartor from commandline and post output to the console (or rather something like  https://gist.github.com/ & post a link here)? It might be lenghty, as it lists all the urls it's trying to access, but it might give us a clue.

**Comment by Krakonos** [comment]
Oh and when you're at it, try to open the links in a browser, to check if you can actually fetch the tile from your place, so we can rule that out.

**Comment by fusionstream** [comment]
Wilco. In about 15 hours. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ladislav Láska <notifications@github.com> Date: 30/05/2016  00:00  (GMT+08:00) To: openstreetmap/merkaartor <merkaartor@noreply.github.com> Cc: fusionstream <fusionstream@gmail.com>, Author <author@noreply.github.com> Subject: Re: [openstreetmap/merkaartor] Bing tiles not showing up on Windows 10 (#99) 
Oh and when you're at it, try to open the links in a browser, to check if you can actually fetch the tile from your place, so we can rule that out.

**Comment by fusionstream** [comment]
Running from the command line produces no output. It's like the process is
forked. I get returned to the prompt after the program starts.

Clicking on the bing link brings me to the bing maps page and I am able to
browse the tiles.

**Comment by Krakonos** [comment]
Bummer. The Windows version does redirect qDebug() and others to god knows here. Could you try with version 0.18.2-93-g7a4e38d ? It's available on https://bintray.com/krakonos/nightly/Merkaartor/0.18.2-93-g7a4e38d/view , 32bit installer will get generated in a few minutes. This should ouput some useful stuff on stdout.

**Comment by fusionstream** [comment]
https://gist.github.com/fusionstream/86616d2315239ad9f6816de94faed474

Nothing much to see though? I tried those links in the debug output and I can definitely get the tiles in my browser.

**Comment by Krakonos** [comment]
Seems allright. I'll dig further.

**Comment by fusionstream** [comment]
Thanks.

Perhaps Microsoft blocked it for Singapore? I know that OSM is blocked (or maybe was; app doesn't work on marshmallow so no idea) on Locus Pro (an android app) but not on some others.

**Comment by Krakonos** [comment]
What do you mean? You said the tiles work in the browser, so I assume they are not blocked.

**Comment by fusionstream** [comment]
Yes they work in the browser. But like my locus app back then, it got blocked only in the app but not on the browser. So perhaps a user agent block?
Is there a physical tile store for merkaartor? Can I browse to it and check that the tiles aren't actually white? 

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ladislav Láska <notifications@github.com> Date: 01/06/2016  00:05  (GMT+08:00) To: openstreetmap/merkaartor <merkaartor@noreply.github.com> Cc: fusionstream <fusionstream@gmail.com>, Author <author@noreply.github.com> Subject: Re: [openstreetmap/merkaartor] Bing tiles not showing up on Windows 10 (#99) 
What do you mean? You said the tiles work in the browser, so I assume they are not blocked.

**Comment by Krakonos** [comment]
There is no physical storage for the tiles. I'd recommend running wireshark, capturing the traffic, and exporting images from there. If you filter out the stream, you can do File -> Export objects -> HTTP

**Comment by fusionstream** [comment]
Wilco


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ladislav Láska <notifications@github.com> Date: 01/06/2016  00:57  (GMT+08:00) To: openstreetmap/merkaartor <merkaartor@noreply.github.com> Cc: fusionstream <fusionstream@gmail.com>, Author <author@noreply.github.com> Subject: Re: [openstreetmap/merkaartor] Bing tiles not showing up on Windows 10 (#99) 
There is no physical storage for the tiles. I'd recommend running wireshark, capturing the traffic, and exporting images from there. If you filter out the stream, you can do File -> Export objects -> HTTP

**Comment by Krakonos** [comment]
Allright, I managed to reproduce the problem on my machine. Just don't ask me how.

Just humor me and try to put this Qt5Core.dll into the directory where Merkaartor is installed, overwriting the existing one: http://stuff.krakonos.org/files/Qt5Core.dll (This is 64bit version, I didn't try with 32bit; have you tried 32bit version?)

**Comment by fusionstream** [comment]
I have tried the 32 bit version but not since I opened this ticket.

The dll placement didn't work sadly. The DLL seemed to be the same file 
size down to the byte if that helps in any way.

**Comment by Krakonos** [comment]
Nah, I think I sent you the wrong one. Here is another one (remove the 0_ ...): 

http://stuff.krakonos.org/files/0_Qt5Core.dll

And yes, it is the same size, but a bit different inside (I'm not really sure what's the difference yet).

**Comment by fusionstream** [comment]
Still got nothing. I'm still on that nightly build btw. Should I upgrade 
or something?

**Comment by Krakonos** [comment]
Strange. I've been experimenting on my machine. I have installed the nightly build, and a build from that machine, from freshly upgraded MSYS2. These should be the same, but they are not.

QtCore5.dll from the local build works, the one from nightly does not.

Did you rename it from 0_QtCore5.dll to QtCore5.dll and rewritten the original one from nightly? Seems strange it has different effect on your system than on mine :-)

**Comment by fusionstream** [comment]
Yep. Renamed. Overwritten.

**Comment by Krakonos** [comment]
I got it. The problem is that QtCore5 does have some hardcoded path and tried to load some plugins at runtime. It's a shame it doesn't tell us there are some missing :-(. There is a tool windeployqt, that might help me.

I'll let you know once I have a solution to test. Thanks for your help debugging this!

**Comment by fusionstream** [comment]
Well I didn't do much so "thanks for debugging" to you!

Cheers,
Shawn.

**Comment by Krakonos** [comment]
Hopefully fixed in 51d51b2, try the 0.18.2-121-g51d51b2 nightly (already generated).

**Comment by fusionstream** [comment]
YES! Thank you so much! So many edits to catch up on now! :D:D:D
